# Generated by Django 3.2.8 on 2021-10-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUrl',
            fields=[
                ('url', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Urls',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('enrolled', models.CharField(blank=True, max_length=20, null=True)),
                ('offered', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.courseurl')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
