# Generated by Django 3.2.8 on 2021-11-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Udemy', 'Udemy'), ('Coursera', 'Coursera')], default='Udemy', max_length=10),
        ),
    ]
