# Generated by Django 3.2.8 on 2021-11-03 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseurl_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.courseurl'),
        ),
        migrations.AlterField(
            model_name='courseurl',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseurl'),
        ),
    ]
