# Generated by Django 3.2.8 on 2021-11-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courseurl_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseurl'),
        ),
    ]
