# Generated by Django 3.2.8 on 2021-11-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courseurl'),
        ),
    ]
